### ISSUE TITLE
Hatch Intake Subsystem

### ISSUE THREAD

**Issue by jmahari** [FRCTeam4500/2019Robot#4]
Need to build the hatch intake sub system

**Comment by NicolasNewman** [comment]
@Octillerysnacker Remove the 4 unneeded functions in the subsystem. There will never be a situation where we need them and they create unnecessary clutter.

**Comment by Octillerysnacker** [comment]
done, I think that's everything

**Comment by NicolasNewman** [comment]
Think again!

1. In your subsystem, any parts that are declared should be private.
2. In RobotMap, you should separate variables by subsystems. Add one of the multi line comments like the one for the drivetrain and put your Hatch variables under there.
3. Since moving a piston is a single movement, isFinished should be true for each commands and instead of execute, you want to use initialized.
4. It looks like you haven't mapped the buttons in OI.

**Comment by Octillerysnacker** [comment]
ok how about now
